# Generated by Django 3.0.5 on 2020-05-28 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('round', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TennisPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('firstname', models.CharField(max_length=15)),
                ('nationality', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('surface', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TournamentEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TennisPlayerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_won', models.IntegerField()),
                ('matches_lost', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TennisPlayer')),
            ],
        ),
        migrations.CreateModel(
            name='MatchStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_ace', models.IntegerField()),
                ('winner_df', models.IntegerField()),
                ('winner_serve_points', models.IntegerField()),
                ('winner_1st_in', models.IntegerField()),
                ('winner_1st_won', models.IntegerField()),
                ('winner_2st_won', models.IntegerField()),
                ('loser_df', models.IntegerField()),
                ('loser_serve_points', models.IntegerField()),
                ('loser_1st_in', models.IntegerField()),
                ('loser_1st_won', models.IntegerField()),
                ('loser_2st_won', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Match')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='loser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loser', to='api.TennisPlayer'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TournamentEvent'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='api.TennisPlayer'),
        ),
    ]
