# Generated by Django 3.0.6 on 2020-06-01 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200531_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='city',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='date',
        ),
    ]
