# Generated by Django 3.0.5 on 2020-06-02 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200602_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='city',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='date',
        ),
    ]
