# Generated by Django 3.0.5 on 2020-06-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200602_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='city',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
