# Generated by Django 3.0.5 on 2020-06-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200602_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='tennisplayerstats',
            name='aces',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='tennisplayerstats',
            name='double_faults',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='tennisplayerstats',
            name='first_in',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='tennisplayerstats',
            name='first_won',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='tennisplayerstats',
            name='others_1st_in',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='tennisplayerstats',
            name='others_2nd_won',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='tennisplayerstats',
            name='others_2st_won',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='tennisplayerstats',
            name='others_breakpoints_faced',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='tennisplayerstats',
            name='others_breakpoints_saved',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='tennisplayerstats',
            name='others_serve_points',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='tennisplayerstats',
            name='second_won',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='tennisplayerstats',
            name='sets_lost',
            field=models.IntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='tennisplayerstats',
            name='sets_won',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='surface',
            field=models.CharField(choices=[('A', 'Acrylic'), ('B', 'Artificial clay'), ('C', 'Artificial grass'), ('D', 'Asphalt'), ('E', 'Carpet'), ('F', 'Clay'), ('G', 'Concrete'), ('H', 'Grass'), ('J', 'Other')], max_length=15),
        ),
    ]
