# Generated by Django 3.0.5 on 2020-06-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200607_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tennisplayerstats',
            name='sets_won',
            field=models.IntegerField(),
        ),
    ]
