# Generated by Django 3.0.5 on 2020-06-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200607_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tennisplayerstats',
            name='aces',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tennisplayerstats',
            name='double_faults',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tennisplayerstats',
            name='first_in',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tennisplayerstats',
            name='first_won',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tennisplayerstats',
            name='others_1st_in',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tennisplayerstats',
            name='others_2nd_won',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tennisplayerstats',
            name='others_2st_won',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tennisplayerstats',
            name='others_breakpoints_faced',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tennisplayerstats',
            name='others_breakpoints_saved',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tennisplayerstats',
            name='others_serve_points',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tennisplayerstats',
            name='second_won',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tennisplayerstats',
            name='sets_lost',
            field=models.IntegerField(),
        ),
    ]
