# Generated by Django 3.0.5 on 2020-06-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200607_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anecdote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('content', models.CharField(max_length=150)),
            ],
        ),
    ]
