# Generated by Django 3.0.5 on 2020-06-08 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_anecdote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchstats',
            name='match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Match'),
        ),
    ]
