# Generated by Django 3.0.5 on 2020-06-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200610_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchstats',
            name='loser_ace',
            field=models.IntegerField(default='1'),
        ),
    ]
