# Generated by Django 3.0.5 on 2020-06-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_matchstats_loser_ace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchstats',
            name='loser_ace',
            field=models.IntegerField(),
        ),
    ]
