# Generated by Django 3.0.5 on 2020-06-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200610_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tennisplayerstats',
            name='serve_points',
            field=models.IntegerField(),
        ),
    ]
