# Generated by Django 3.0.5 on 2020-06-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meteo',
            name='date',
        ),
        migrations.AddField(
            model_name='meteo',
            name='date_time',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='anecdote',
            name='content',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='anecdote',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
