# Generated by Django 3.0.5 on 2020-06-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200615_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meteo',
            name='date_time',
            field=models.CharField(max_length=50),
        ),
    ]
