# Generated by Django 3.0.5 on 2020-06-16 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200615_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('location_latitude', models.DecimalField(decimal_places=8, max_digits=15)),
                ('location_longitude', models.DecimalField(decimal_places=8, max_digits=15)),
                ('last_load', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='meteo',
            name='city',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='api.City'),
        ),
    ]
