# Generated by Django 3.0.5 on 2020-06-16 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200616_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meteo',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.City'),
        ),
    ]
