# Generated by Django 3.0.5 on 2020-06-19 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20200616_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tennisplayerstats',
            options={'managed': False},
        ),
        migrations.AlterField(
            model_name='city',
            name='last_load',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
