# Generated by Django 3.0.5 on 2020-06-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20200619_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player_stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ace', models.IntegerField()),
                ('df', models.IntegerField()),
                ('serve_points', models.IntegerField()),
                ('first_in', models.IntegerField()),
                ('first_won', models.IntegerField()),
                ('second_won', models.IntegerField()),
                ('first_serve_success_percentage', models.DecimalField(decimal_places=8, max_digits=15)),
                ('first_serve_won_percentage', models.DecimalField(decimal_places=8, max_digits=15)),
                ('second_serve_won_percentage', models.DecimalField(decimal_places=8, max_digits=15)),
                ('ace_percentage', models.DecimalField(decimal_places=8, max_digits=15)),
                ('df_percentage', models.DecimalField(decimal_places=8, max_digits=15)),
                ('firstname', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('player_id', models.IntegerField()),
            ],
            options={
                'db_table': 'player_stats',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='tennisplayerstats',
            options={},
        ),
    ]
