# Generated by Django 3.0.5 on 2020-06-20 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20200620_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prediction',
            old_name='match_id',
            new_name='match',
        ),
        migrations.RenameField(
            model_name='prediction',
            old_name='player1_id',
            new_name='player1',
        ),
        migrations.RenameField(
            model_name='prediction',
            old_name='player2_id',
            new_name='player2',
        ),
    ]
